env:
  shared-node-browser: true
  es2020: true

ignorePatterns:
  - dist
  - "*.js"

extends:
  - plugin:@lichtblick/base
  - plugin:@lichtblick/jest

overrides:
  - files: ["*.ts", "*.tsx"]
    extends:
      - plugin:@lichtblick/typescript
    parserOptions:
      project: ./tsconfig.json
    rules:
      #There are enums in this project that don't follow this rule and we're not sure about the side effects of changing it. It can be revisited in the future
      "@typescript-eslint/prefer-literal-enum-member": off
